const titleProject = 'Оценка стоимости';
console.log(typeof titleProject);
const screensValue = 'шаблонные, с уникальным дизайном, с анимациями';
console.log(typeof screensValue);
const screenPrice = 12000;
console.log(typeof screenPrice);
const percentage = 15;
console.log(typeof percentage);
const fullPrice = 30000;
console.log(typeof fullPrice);
const responsive = true;
console.log(typeof responsive);